#+TITLE:CSC100 Bookmarks 
#+AUTHOR:Marcus Birkenkrahe
#+SUBTITLE:CSC100 web bookmarks 
#+STARTUP:overview
#+OPTIONS:hideblocks
* Bookmarks
** What is this about?

   When I find an interesting article or video, I share it here. Most
   of these are possible starting points for a short presentation, or
   may be useful for your application research.

   I usually look at the articles in some detail (though I rarely work
   through them - that would be your job), and assign a label for the
   difficulty level Lvl = 0 (simple), 1 (moderate), 2 (difficult), or 3
   (hard). Sites or tutorials aren't labeled by difficulty.

   Papers can be hard for different reason: length, technical
   vocabulary, writing style, mathematics, number of citations etc. If
   you find any of these interesting and want to use them for your
   research, you might ask me why I assigned a particular level.

** C Programming tutorials (free)

   The freeCodeCamp course uses our environment (Code::Blocks).
   
   * [[https://youtu.be/KJgsSFOSQv0][C Programming Tutorial for Beginners (4hrs)]] - freeCodeCamp
     
   * [[https://youtu.be/Bz4MxDeEM6k][C Programming All-in-One Tutorial Series (10 hrs)]] - Caleb Curry
     I looked at the first few - fairly slow, funny
   * [[https://youtu.be/2NWeucMKrLI][C Programming tutorial (5hrs)]] - thenewboston

** Udemy course (not free)

   I only know about these because I bought them a while back.
   
   * [[https://blog.udemy.com/what-is-c-programming/][What is C programming? Learn the basics (2021)]]
   * [[https://www.udemy.com/course/c-programming-for-beginners/][Udemy Course: Huw Collingbourne (2019)]]

** IDEs

   * [[https://codelite.org][CodeLite]]: "CodeLite is an open source, free, cross platform IDE
     specialized in C, C++, PHP and JavaScript (mainly for backend
     developers using Node.js) programming languages which runs best
     on all major Platforms ( OSX, Windows and Linux)."
   * Download 64-bit version - exe file. Run it. Accept warning
     condition. Accept license. Accept path suggestions. Have
     additional shortcuts created (desktop and launcher).
   * Welcome screen asks for your profile (intended use): pick C/C++
     development.
   * Setup compilers: scan for existing compilers or install MinGW
     compiler. Download newer (stable) version if you like. Check out
     forums and wiki (both on the web).
** What is a programming language

   A lot of vocal fry [[https://www.codecademy.com/resources/blog/programming-languages/][in this video]] but you can also just read the
   transcript. Includes some good links, like [[https://pypl.github.io/PYPL.html][PYPL]]. I have started the (free) C++
   course from Codeacademy (they're a big online course provider).  

** [[https://youtu.be/48JlgiBpw_I][Absolute beginner's guide to Emacs]] (1 hr 15 min)

   * [[https://systemcrafters.net/emacs-essentials/absolute-beginners-guide-to-emacs/][Notes]] (Emacs Org mode file committed to GitHub)

   
