#+TITLE:Compiler dependencies
#+AUTHOR:Marcus Birkenkrahe
#+SUBTITLE:printf cp. Collinbourne's C for beginners on Udemy
#+STARTUP: overview hideblocks
#+OPTIONS: toc:nil num:nil ^:nil
* Correct ~printf~ command

  This example demonstrates one of C's weaknesses using the ~printf~
  function. The first code block contains the correct command.

  #+name:pi0
  #+begin_src C :main yes :includes stdio.h :exports both
    printf("%d bottles of beer on the %s", 20, "wall\n");
  #+end_src

  #+RESULTS: pi0
  : 20 bottles of beer on the wall

* Wrong format identifier

  The machine's response to errors is highly compiler-dependent. On
  Linux Raspbian with gcc 8.3.0, the following error leads to a
  ~Segmentation fault~ at run time[fn:1]. On Windows 10 with MinGW-W64
  gcc 8.1.0, there is no output but also no complaint[fn:2].

  #+name:pi1
  #+begin_src C :main yes :includes stdio.h 
    printf("%s bottles of beer on the %s", 20, "wall\n");
  #+end_src

* Wrong number of data for input

  In this example, two arguments are formatted, but three data are put
  in, namely an extraneous string[fn:3].

  #+name:pi2
  #+begin_src C :main yes :includes stdio.h :exports both
    printf("%d bottles of beer on the %s", 20, "wall", "wall" );
  #+end_src

  #+RESULTS: pi2
  : 20 bottles of beer on the wall

  Only when using the ~-Wall~ (all warnings) flag, will the compiler
  show these warnings (not in org-mode, only during a shell
  compilation):

  #+begin_example
#$ gcc -Wall -o perr printf_error.c
printf_error.c: In function ‘main’:
printf_error.c:9:8: warning: too many arguments for format [-Wformat-extra-args]
 printf("%d bottles of beer on the %s", 20, "wall", "wall" );
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  #+end_example
  
* Org-mode

  | Header arguments used |
  |-----------------------|
  | :main yes             |
  | :includes stdio.h     |
  | :exports both         |
  | :flags -Wall          |

* Footnotes

[fn:3]What the computer really stores when an extra string is put in
which was not reserved is a so-called ~NULL~ string. What it contains
is completely unpredictable. This can lead to serious issues when some
other program tries to access the memory location where ~NULL~ is
stored, in the belief that its contents are known.

[fn:2]Setting the compiler flag ~-Wall~ generates a suitable warning
but the compilation is not halted:
#+begin_example
$ gcc -Wall -o pi1 pi1.c 
pi1.c: In function 'main':
pi1.c:9:10: warning: format '%s' expects argument of type 'char *', but argument 2 has type 'int' [-Wformat=]
 printf("%s bottles of beer on the %s", 20, "wall\n");
         ~^                             ~~
         %d
#+end_example

[fn:1]"Segmentation" relates to the computer's memory management. The
background is that the compiler needs to reserve memory for
operations, and it does this based on the data types. If, as in the
example, a reservation for a string type has been made (~%s~ is the
format identifier for a strong), but then integer data (~20~) are put
in, the memory segmentation is faulty.
