#+TITLE:History of C
#+AUTHOR:Marcus Birkenkrahe
#+SUBTITLE:CSC100 Introduction to programming in C/C++
#+STARTUP:overview
#+OPTIONS: toc:1
#+OPTIONS:hideblocks
* What will you learn?

  * What is C?
  * What is its origin?
  * What is its importance?
  * What's the difference to C++?
  * Why are we not just learning C++?
  * What are C's strengths and weaknesses?
  * Why are you learning C from me?
  * What's next in the course?

  Source: [[king][King (2008) ch.1]]
  -----
* What is C?

  C is a widely used high-level programming language developed in the
  early 1970s at Bell Laboratories.
* Where does C come from?

  Cp. K&R ([[kr][Kernighan/Ritchie, 1978]])

* How important is C?

* What is the difference between C and C++?

  Source: [[lemonaki][Lemonaki, 2021]]

  Ritchie: [[https://en.wikipedia.org/wiki/Space_Travel_(video_game)][Space Travel game 1969]]

  Torvalds: [[https://medium.com/nerd-for-tech/linus-torvalds-c-is-really-a-terrible-language-2248b839bee3][C++ is really a terrible language]]

* Why are we not just learning C++?

* Why am I teaching C/C++?

* What's next?

  * Getting started: Infrastructure (shell, compiler, editor)
  * First program: "hello world"
  -----
* References

  King (2008). C Programming - A Modern
  Approach. Norton. [[http://knking.com/books/c2/index.html][Online: knking.com]].

  Kernighan/Ritchie (1978). The C Programming
  Language. Prentice Hall. [[https://en.wikipedia.org/wiki/The_C_Programming_Language][Online: wikipedia.org]].

  Lemonaki, Dionysia (November 4, 2021). C vs. C++ -
  What's The Difference [blog]. URL: [[https://www.freecodecamp.org/news/c-vs-cpp-whats-the-difference/][freecodecamp.org.]]
  
